export const SEEKER_ONBOARD_SUCEESS = "SEEKER_ONBOARD_SUCEESS";
export const SEEKER_ONBOARD_FAILED = "SEEKER_ONBOARD_FAILED";
export const PROVIDER_ONBOARD_SUCEESS = "PROVIDER_ONBOARD_SUCEESS";
export const PROVIDER_ONBOARD_FAILED = "PROVIDER_ONBOARD_FAILED";
export const API_RESPONSE_SUCEESS = "API_RESPONSE_SUCEESS";
export const API_RESPONSE_FAILED = "API_RESPONSE_FAILED";
export const SAVE_INDUSTRIES = "SAVE_INDUSTRIES";
export const API_RESPONSE_RESET = "API_RESPONSE_RESET";
