/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: "us-east-1",
	aws_cognito_region: "us-east-1",
	aws_user_pools_id: "us-east-1_e5AK0SiHg",
	aws_user_pools_web_client_id: "43cog0kj4oklmv71ump1objdle",
	oauth: {
		domain: "tax-portal.auth.us-east-1.amazoncognito.com",
		scope: ["aws.cognito.signin.user.admin", "email", "openid", "profile"],
		redirectSignIn: "https://dev.taxglobal.co/processing",
		redirectSignOut: "https://dev.taxglobal.co/login",
		responseType: "code",
	},
	federationTarget: "COGNITO_USER_POOLS",
	aws_cognito_username_attributes: ["EMAIL"],
	aws_cognito_social_providers: ["GOOGLE"],
	aws_cognito_signup_attributes: ["NAME", "EMAIL"],
	aws_cognito_mfa_configuration: "OFF",
	aws_cognito_mfa_types: [],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: [
			"REQUIRES_LOWERCASE",
			"REQUIRES_UPPERCASE",
			"REQUIRES_NUMBERS",
			"REQUIRES_SYMBOLS",
		],
	},
	aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
